### ISSUE TITLE
OptionalValue as an attribute instead of a new type

### ISSUE THREAD

**Issue by LorenzGit** [BoomDAO/ICP.NET#40]
For the sake of keeping the model as pure as possible and standardize serialization, is it possible to change the OptionalValue so that it will be an attribute instead of a new type?

```c#
// Current translation:
[CandidName("quality")]
public OptionalValue<UInt16> Quality { get; set; }

// Can this be written as:
[CandidName("quality"), OptionalValue]
public ushort? Quality { get; set; }
```

**Comment by Gekctek** [comment]
Have the option of `override-optional-value` in the client generation as an experimental feature
