### ISSUE TITLE
C# Variant Changes

### ISSUE THREAD

**Issue by Gekctek** [BoomDAO/ICP.NET#92]
From @LorenzGit on discord

I would like to suggest a change in the way C# classes of Variants are parsed. The reason is because this would allow us to manually create classes with generics.
In line 428 of IResolvableTypeInfo.cs a list of properties is already retrieved, that should contain all the information necessary to achieve this, would require a few code changes in that area. This pattern should work fine also for C# generated files that do not use generics. 
![image](https://github.com/BoomDAO/ICP.NET/assets/1934953/281307d6-fde9-410e-9e04-9a5783323d71)
![image](https://github.com/BoomDAO/ICP.NET/assets/1934953/b09df940-b74b-4966-8dc0-8928d8c1a574)

**Comment by Gekctek** [comment]
@LorenzGit does this fit your needs vs just having error being a string?

Also do you need them to be accessor properties or can they be AsOk()/AsError() but still be generic?
 
```
public  class ApiResult<TOk, TError>
{
  public Tag Tag {get; private set; }
  public object Value {get; private set;}
  public TOk Ok
  {
    get => tag == Tag.Ok ? (T) this.value : default;
    set => (tag, this.value) = (Tag.Ok, value);
    }
  public TError TError
  {
    get => tag == Tag.Ok ? (T) this.value : default;
    set => (tag, this.value) = (Tag.Ok, value);
    }
    
}
```

**Comment by LorenzGit** [comment]
My proposal was simply to not use (Type) inside an Attribute, since the current version of C# in Unity doesn't allow for Generics in Attribute.

**Comment by Gekctek** [comment]
Done. Now types are based off of the return type of functions or the type of a property. No types in the attributes anymore or on the enum
